Editorsection
andynarf/Positioning_and_Floating_Elements pull request #1
Opened 2019-07-16 22:49 UTC by andynarf

2019-07-18 07:55 UTC, mosaaleb requested changes
### Amazing work @andynarf, @AndresFMoya :clap:

#### The UI is neat and clean. Kudos on using separate `normalize.css` file. Your code is organized and easy to read. Still some requirements needs to be handled first before merging.

##### Navigation bar:
- [x] Uses the `<nav>` tag for more semantic html
- [x] Has the `hamburger` and `search` icons in the leftmost side, you can use font awesome.

##### Footer
- [x] The NYTimes logo is a link.


##### General:
- [x] Let's fill the relevant information the `readme.md` file.
- [x] Let's make sure that we follow the style guidelines by adding [stickler](https://github.com/microverseinc/linters-config/tree/master/css), and then make sure that all checks have passed.

Please submit a new code review once you handle these requirements. 

Keep up the good work team. Happy coding :computer:

2019-07-18 07:55 UTC, mosaaleb commented on style.css
> +    margin-right: 9%;
`g-ai1` through `g-ai4` have the same style properties, we can remove alot of duplicate code with a class having the same properties, and give custom style properties to those who need a little change. Also `g-ai5` through `g-ai8`.

2019-07-18 07:55 UTC, mosaaleb commented on style.css
> +    display: flex;
The default value of `flex-direction` is row, so we don't actually need this line.

2019-07-18 07:55 UTC, mosaaleb commented on style.css
> +    width: 100%;
Also, the default value of `justify-content` is `flex-start`

2019-07-18 07:59 UTC, mosaaleb commented on style.css
> +    justify-content: space-between;
The default value of `flex-direction` is row, so we don't actually need this line.

2019-07-18 22:36 UTC, andynarf commented
we had a lot of failures with our normalize.css on stickler. 
I don't know they are actual issues.

2019-07-18 22:41 UTC, mosaaleb commented
All of them had to do with style guidelines. You can check the errors in the checks tab on top of this pull request page.

2019-07-18 22:56 UTC, andynarf commented
yeah, i know , ok, I'll just use a different css reset file, since I see no point in correcting every single line on that one.

2019-07-19 17:41 UTC, andynarf commented
there, we fixed everything =D

2019-07-19 20:48 UTC, samgaco commented
Hi, @andynarf  and @mosaaleb :vulcan_salute: 

Good work! Still, some things left to add;

* You should implement the subscribe section in the footer and the bottom part of the footer should include links with copyright, contact us, help, etc

![left](https://user-images.githubusercontent.com/34820784/61564488-d81aab00-aa76-11e9-905d-3bd15b68edd7.jpg)

* Any section including paragraphs in your project should be enclosed within the` <section> `tag. In the case of the "Editor's picks" and the "Sign up" button they should also include the `<aside>` tag. Learn more about it here: https://www.w3schools.com/html/html5_semantic_elements.asp

* Correct the errors shown in https://validator.w3.org/ for the HTML file

Commit the changes and submit back for a code review when you are done. Happy Coding! :muscle:

2019-07-23 07:02 UTC, bolah2009 commented
PR currently reviewed

2019-07-23 07:41 UTC, bolah2009 requested changes
# Nice Job Team! :clap: 

You've done an awesome Job :muscle:

- A few changes to be made, please check the screenshot below and kindly make changes accordingly. Check the [original site](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) for more details.

| Current | Preffered |
| :---:   | :---:   |
| ![syb btn current](https://user-images.githubusercontent.com/36057474/61691509-9f532e00-ad23-11e9-8656-309e73733790.png)  | ![sub login preffered](https://user-images.githubusercontent.com/36057474/61691535-aaa65980-ad23-11e9-82ba-abc27f7eb074.png)  |
| ![inflation current](https://user-images.githubusercontent.com/36057474/61691566-ba25a280-ad23-11e9-9b47-b9bfebbefb61.png)  |  ![pos-n-flo](https://user-images.githubusercontent.com/36057474/61691585-c90c5500-ad23-11e9-91c7-e976fc3fdec9.png) |
| ![read more btn current](https://user-images.githubusercontent.com/36057474/61691616-d88b9e00-ad23-11e9-818d-a39b0d29dd06.png)  | ![read button preffered](https://user-images.githubusercontent.com/36057474/61691720-138dd180-ad24-11e9-8ec0-c4591857c1e6.png)  |
| NOT FOUND  | ![editor's pick ](https://user-images.githubusercontent.com/36057474/61691779-34562700-ad24-11e9-989a-ab37f0c60201.png)  |
| NOT FOUND  | ![sign up](https://user-images.githubusercontent.com/36057474/61691798-4041e900-ad24-11e9-8ec4-8074cbe015dd.png)  |
| ![m popular sec nty current](https://user-images.githubusercontent.com/36057474/61691840-5485e600-ad24-11e9-90f4-3ec928aa87f3.png) |  ![nyt popular preffered](https://user-images.githubusercontent.com/36057474/61691978-ae86ab80-ad24-11e9-8bbe-ab3ac2806804.png) |
| ![editor pick sec nyt](https://user-images.githubusercontent.com/36057474/61692011-c4946c00-ad24-11e9-96f7-cb1bbe03430a.png) | ![nyt editor preffered](https://user-images.githubusercontent.com/36057474/61692053-d7a73c00-ad24-11e9-9173-d9bf601331b1.png)  |
| ![subcribe sec nyt current](https://user-images.githubusercontent.com/36057474/61692177-10dfac00-ad25-11e9-976b-ced52e6f8b89.png)  | ![nyt footer preffered](https://user-images.githubusercontent.com/36057474/61692215-22c14f00-ad25-11e9-9926-067b71704765.png)  |

You have done an awesome job, consider making these changes, taking into consideration the **positioning and styling** of the above-screenshotted components of the page.

Good luck with your next submission :+1: 

Cheers
Bola

2019-07-24 00:27 UTC, bolah2009 approved these changes
# Congratulations Team! :tada:

You've done an awesome Job :muscle:

### The [page](https://raw.githack.com/andynarf/Positioning_and_Floating_Elements/editorsection/index.html) looks good to me, however check out the code with [HTML Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fandynarf%2FPositioning_and_Floating_Elements%2Feditorsection%2Findex.html) and on 100% browser zoom.


Good luck with your next project
Keep it up :star2:

Cheers
Bola

2019-07-24 15:58 UTC, merged